const RUDE_WORDS = [
  "anal",
  "anus",
  "arse", "arses", "arsehole", "arseholes", "arsehat",
  "ass", "asses", "asshat", "asshats",
  "asshole", "assholes",
  "asswipe", "asswipes",
  "balls", "ballsack",
  "bastard", "bastards",
  "bellend",
  "bimbo", "bimbos",
  "bitch", "bitches", "bitching", "bitchy",
  "blowjob", "blowjobs",
  "bollocks",
  "boner",
  "boob", "boobs",
  "bugger",
  "bullshit",
  "chinc",
  "chink",
  "clit", "clits", "clitoris",
  "cock", "cocks", "cockhead", "cocksucker", "cocksucking",
  "cooch",
  "coon",
  "cooter",
  "crap",
  "cum", "cumming", "cumshot", "cumslut",
  "cunt", "cunts",
  "dago",
  "damn", "dammit",
  "dick", "dicks", "dickhead", "dickheads", "dickface",
  "dildo", "dildos",
  "dipshit", "dipshits",
  "douche", "douchebag", "douchebags",
  "dumbass", "dumbasses",
  "ejaculate", "ejaculated", "ejaculating", "ejaculation",
  "fag", "fags", "faggot", "faggots",
  "fatass", "fatasses",
  "felch", "felching",
  "fellatio",
  "fuck", "fucks", "fucking", "fucked", "fucker", "fuckers", "fuckface", "fuckhead",
  "gook",
  "goddamn", "goddammit",
  "halfbreed", "half-breed",
  "handjob", "handjobs",
  "hell",
  "holy shit",
  "honky",
  "hump", "humping",
  "jackass", "jackasses",
  "jap",
  "jerk", "jerks", "jerkass",
  "jizz",
  "kike",
  "knob", "knobhead",
  "kraut",
  "labia",
  "lardass",
  "masturbate", "masturbating", "masturbation",
  "mick",
  "motherfucker", "motherfuckers", "motherfucking",
  "muff",
  "nazi",
  "nigga", "nigger", "niggers", "niggas",
  "nip",
  "nipple", "nipples",
  "orgasm", "orgasming",
  "paki",
  "pecker",
  "penis", "penises",
  "phallus",
  "piss", "pissed", "pissing", "pissed off",
  "polack",
  "porn", "porno", "pornography",
  "prick", "pricks",
  "prostitute",
  "pube", "pubes", "pubic",
  "pussy", "pussies",
  "queef",
  "queer", "queers",
  "raghead",
  "redneck", "rednecks",
  "retard", "retards", "retarded",
  "rimjob",
  "scrotum", "scrotal",
  "semen",
  "sex",
  "shit", "shits", "shitting", "shithead", "shitheads", "shitbag", "shitbags", "shitface", "shitfuck",
  "skank",
  "slag",
  "slut", "sluts", "slutty",
  "smut",
  "snatch",
  "son of a bitch",
  "spic", "spick", "spics",
  "spunk",
  "testicle", "testicles", "testicular",
  "tit", "tits", "titties",
  "tosser",
  "towelhead",
  "turd", "turds",
  "twat",
  "twats",
  "urethra",
  "uterus",
  "vagina", "vaginal",
  "vibrator",
  "vulva",
  "wank", "wanking", "wanker", "wankers", "wankstain",
  "wetback", "wetbacks",
  "whore", "whores",
  "wog",
  "yid",
];

const pattern = new RegExp(`\\b(${RUDE_WORDS.map(w => w.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")).join("|")})\\b`, "gi");

export function censorText(text: string): string {
  return text.replace(pattern, (match) => "*".repeat(match.length));
}
